# Generated by Django 3.0.5 on 2023-03-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_bloodrequest_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
